키변경
ECONO-UNION/union-mentoring-1-Unity pull request #15
Opened 2021-08-21 13:40 UTC by JuicyPark

InputManager.cs
- ChangeKey() : PlayerPrefs를 이용해서 사용자가 설정한 키를 저장

PageKeyChange.cs
- 키변경을 시키는 Panel에 붙은 스크립트
- InputSystem에서 정의한 키들을 전부 표시해줌
- GetPressedKey() : 사용자가 변경할 키를 입력시 현재 선택된 KeyChanger에게 KeyCode값을 넘겨줌 
![image](https://user-images.githubusercontent.com/31693348/130323483-054e1107-3b47-4a2b-8124-dacaee9e94ee.png)

KeyChanger.cs
- 현재 설정된 키값을 보여줌
![image](https://user-images.githubusercontent.com/31693348/130323591-a6bbf351-59f3-4b4d-bbb3-f61ea5894ce1.png)

2021-08-22 01:38 UTC, Parkhyunseo requested changes
고생하셨습니다!

2021-08-22 01:38 UTC, Parkhyunseo commented on Union/Assets/Scripts/UI/KeyChanger.cs
> +            _codeName.text = "������ Ű�� �����ּ���";
text 에러!

2021-08-22 01:38 UTC, Parkhyunseo commented on Union/Assets/Scripts/UI/KeyChanger.cs
> +        public void OnClickChangeReady()
Ready가 붙은 이유가 뭘까요?

2021-08-22 01:38 UTC, Parkhyunseo commented on Union/Assets/Scripts/UI/PageKeyChange.cs
> +        private void ExecuteKeyChanger(KeyChanger keyChanger)
KeyChager를 실행한다는게 단어가 조금 어색한 것 같네요.
그리고 저는 인자값에 KeyChanger가 있으면 이름에서는 빼는편입니다

2021-08-22 01:38 UTC, Parkhyunseo commented on Union/Assets/Scripts/UI/KeyChanger.cs
> +    public class KeyChanger : MonoBehaviour
UI와 실제 기능이 분리될 필요가 있어보입니다.

2021-08-22 01:38 UTC, Parkhyunseo commented on Union/Assets/Scripts/UI/KeyChanger.cs
> +        public void Set(KeyName name, KeyCode code, Action<KeyChanger> onClickCallback)
Set함수가 꼭 필요한지 생각해보고 생성자로 뺄 수 있으면 빼면 좋습니다

2021-08-22 01:38 UTC, GyutaeLee requested changes
고생하셨습니다.

2021-08-22 01:38 UTC, GyutaeLee commented on Union/Assets/InputSystem/AxisInput.cs
> +        private KeyInput _postiveKey;
positive << 오타가 있습니다

2021-08-22 01:38 UTC, GyutaeLee commented on Union/Assets/InputSystem/Editor/InputSystemEditor.cs
> +            string path = $"Assets/Resources/{_directory}/{_settingName}.asset";
고정된 경로값이면 const 로 변경해주면 좋을듯합니다.

2021-08-22 01:38 UTC, GyutaeLee commented on Union/Assets/InputSystem/InputManager.cs
> +            if (!KeyInputs.ContainsKey(name))
early return 이 가능해보이는 로직인데, 여러분은 이러한 경우에 early return을 선호하시는지 궁금합니다.

2021-08-22 01:38 UTC, GyutaeLee commented on Union/Assets/Scripts/UI/KeyChanger.cs
> +            _codeName.text = "������ Ű�� �����ּ���";
텍스트가 깨졌습니다.

2021-08-22 01:50 UTC, Parkhyunseo commented on Union/Assets/Scripts/UI/PageKeyChange.cs
> +                var keyChanger = Instantiate(_keyChangerPrefab, transform);
UI는 Instantiate하지말고 로직을 생성

2021-08-22 01:58 UTC, JuicyPark commented on Union/Assets/Scripts/UI/PageKeyChange.cs
> +                var keyChanger = Instantiate(_keyChangerPrefab, transform);
1. KeyChanger가 픽스되게하는방법
2. PageKeyChange의 프리펩을 InputSystem이 수정하는 방법

2021-08-22 15:56 UTC, JuicyPark commented
두분 말씀해주신 부분들 반영했습니다

1. 규태말대로 파일경로 const형식으로변환했고 (Path.Combine())
2. 현서말대로 KeyChange 부분 View부분 Logic 부분 분리했습니다
![image](https://user-images.githubusercontent.com/31693348/130361622-ee0b0490-3180-4584-92c5-c9df295229ee.png)
KeyChanger.cs -> Logic 담당
KeySetting -> View 담당
KeyMapElement (Non Mono) -> 데이터

2021-08-24 12:25 UTC, GyutaeLee approved these changes

2021-09-01 12:31 UTC, Parkhyunseo approved these changes

2021-09-01 12:31 UTC, merged