Csv Reader 클래스 추가
ECONO-UNION/union-mentoring-1-Unity pull request #17
Opened 2021-08-29 05:31 UTC by GyutaeLee

1. Csv 파일은 항상 "Resrouces/Csv/" 경로 하위에 배치해야 함
2. Csv Reader를 생성하면서 하위 Csv Path를 입력함
3. Read() 진행 : 따로 둔 이유는, 데이터가 필요하거나 읽고 싶은 시점에 읽기 위해서
4. GetInfoID & GetData 를 통해 데이터 파싱

2021-08-29 16:17 UTC, Parkhyunseo reviewed
이번에도 코멘트만 남겼습니다~

2021-08-29 16:17 UTC, Parkhyunseo commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +        private static class Constants
내부에서만 사용하는 상수일 경우 따로 클래스 안빼기로 저번에 얘기했던 기억이 있습니다!

2021-08-29 16:17 UTC, Parkhyunseo commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +            TextAsset data = Resources.Load(fullCsvPath) as TextAsset;
TextAsset data = Resources.Load<TextAsset>(fullCsvPath);
형태를 선호하는데

둘 차이는 정확히 어떤지 모르겠네요

2021-08-29 16:17 UTC, Parkhyunseo commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +            this._data = new List<Dictionary<string, string>>();
매번 생성하는 것보다 data를 생성해놓고 Clear하고 다시 담는 방식은 어떨까요

2021-08-30 00:45 UTC, JuicyPark requested changes

2021-08-30 00:45 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +        public T GetData<T>(string key, int infoID)
제네릭 T에 대해 형식제한조건 where이 없어서 어떤클래스를 이용하든 사용이 가능할텐데 ex : GetData<Junsu> 이렇게 했을때 값이 정상적으로 보존이 되지 않을것 같습니다.

2021-08-30 00:45 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +        private List<Dictionary<string, string>> _data;
아래 코드들을 봤을때 data의 자료형은 List<Dict<str.,str>>이 아닌 Dic<str,str> 인것 같아서 네이밍이 _datas가 맞는것 같습니다

2021-08-30 00:45 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +        public T GetData<T>(string key, int infoID)
현재 이 클래스에서 data라는 이름의 자료형은 위에서도 말했듯 Dict<str,str> 인것 같은데 함수이름이 GetData로 하면 해당 자료형Dict<str,str> 반환 해야할것 같습니다.
1. data의 자료형을 바꾸거나
2. data 라는 이름을 바꾸거나
3. 해당 함수의 이름을 바꾸거나해야 혼동을 줄일수 있을것 같습니다.

2021-08-30 13:44 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +        private static class Constants
기존 코드를 수정하면서 다른 곳에서 한 함수로 모은 걸 인지 못했네요!
수정했습니다.

2021-08-30 13:48 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +            TextAsset data = Resources.Load(fullCsvPath) as TextAsset;
Load에서 불러오는 형식이 UnityEngine.Object 인데 자동으로 변환이 되나보군요?!

그와 별개로 프로그래머가 무의식적으로 타입 변환을 놓쳐서 에러가 생기는 경우를 방지하기 위해 명시적으로 적어주는 것을 선호하는 편이긴 합니다.
c#에서는 대부분 자동으로 변환을 해주는걸까요?

이에 대해 회의 때 이야기를 나누어보면 좋을거 같습니다!

2021-08-30 13:53 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +            this._data = new List<Dictionary<string, string>>();
관성적으로 참고 코드를 그대로 사용한 실수네요!
data 가 null인 경우에만 생성하고, null이 아닌 경우에는 Clear() 하도록 수정하겠습니다.

2021-08-30 13:53 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +        private List<Dictionary<string, string>> _data;
네! 그게 더 직관적인거 같습니다. 수정하겠습니다!

2021-08-30 13:56 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +        public T GetData<T>(string key, int infoID)
현재 csv reader에서는 int, long long, float, double, string 만을 읽어오려고 합니다.

where 형식을 사용하려고 구글링을 해보았는데,  해당 자료형에 관한 제약은 찾을 수가 없었습니다.
혹시 관련된 방법에 대해 조언을 해주실 수 있을까요?

2021-09-01 12:45 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +            TextAsset data = Resources.Load(fullCsvPath) as TextAsset;
TextAsset data = Resources.Load\<TextAsset>(fullCsvPath);

제네릭 형식으로 하는 것으로 합의했습니다. (컴파일 타임에 형변환 하도록)

2021-09-16 01:15 UTC, JuicyPark requested changes

2021-09-16 01:15 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/ClassMaker.cs
> +            File.WriteAllText(writePath, classStringBuilder.ToString());
![image](https://user-images.githubusercontent.com/31693348/133530076-9b08f5a5-919f-47e7-8a77-9a2c279a0d7f.png)
이쪽 라인에서 폴더못찾는 에러가 뜨는것 같습니다

2021-09-16 01:15 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +    public class Reader <T> where T : class
데이터를 참조하는 Monster가 100마리 있다고 하면, 100마리 Monster가 모두 new Reader< MonsterInfo >를 해서 데이터를 추출한뒤 딕셔너리에 넣는 로직을 거쳐야할것같습니다.

저는 이렇게 개선해보는걸 생각했는데 어떤까요? DataManager를 만들어서 1번 몬스터가 호출을하면 그때 딕셔너리에 저장을 해두면 2번 몬스터가 사용할때는 이미 DataManager에 데이터가 있기때문에 그걸 쓰면됨. (캐싱방법)
DataManager.Instance.GetData< MonsterInfo >( index ) 로 받아오거나
DataManager.Instance.GetDatas< MonsterInfo >( ) 해당 딕셔너리를 전부 받아오는것도 있으면 좋을것 같습니다.

++
DataManager 속의 Dictionary는
Dictionary < T , Dictionary < int , T > > 이런식으로 생각했습니다

2021-09-16 01:15 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +    public class Reader <T> where T : class
두번째로는
public class Reader <T> where T : class
가 어떤 class든 상관없이 접근이 가능한것 같아서 이런식으로 접근제한을 두는건 어떨까요?
![image](https://user-images.githubusercontent.com/31693348/133533548-6f80eddf-73af-4ec3-a801-675ec1cdc774.png)

2021-09-16 03:39 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +            TextAsset data = Resources.Load(fullCsvPath) as TextAsset;
이부분 저번 리뷰 반영되지 않은것 같습니다

2021-09-16 13:31 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/ClassMaker.cs
> +            File.WriteAllText(writePath, classStringBuilder.ToString());
맥에서 작업할 때와 윈도우에서 경로를 불러오면 나오는 텍스트가 달라서 발생한 이슈였네요.
(윈도우에서는 '\(백슬래시)'를 불러오고, 맥에서는 '/'을 불러옴)

경로를 넣는 방식을 변경해서 해결했습니다.

2021-09-16 13:33 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +    public class Reader <T> where T : class
[1]번 코멘트
- 이번에 이 풀리퀘가 메인에 합쳐지면, Player와 Enemy에 csv 데이터를 붙이면서 따로 [Storage] 클래스를 만들어서 데이터를 저장(캐싱)한 후에 사용하는 코드를 추가할 예정이었습니다.
적어주신 방법과 비슷한 방식으로 진행하려고 설계 중이고, 디테일한 부분에 대해 고민하고 있는데 풀리퀘 후에, 다음 작업 때 추가하도록 하겠습니다.

[2]번 코멘트
- 아주 좋은 방법인거 같습니다! 바로 반영하겠습니다. 감사합니다.

2021-09-16 13:34 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +            TextAsset data = Resources.Load(fullCsvPath) as TextAsset;
as 로 런타임에 불러오지 않고, 제네릭 형식으로 컴파일 타임에 불러오도록 수정했습니다.

2021-09-16 13:49 UTC, JuicyPark approved these changes

2021-09-17 05:14 UTC, Parkhyunseo approved these changes

2021-09-23 12:27 UTC, merged