Csv Storage 추가
ECONO-UNION/union-mentoring-1-Unity pull request #25
Opened 2021-09-26 05:03 UTC by GyutaeLee

- Class 하나마다 Storage Singleton Instance가 생성됨
- generic 형식으로 Class와 info id를 기준으로 데이터를 불러옴

2021-09-26 06:26 UTC, JuicyPark requested changes
고생하셨습니다.
구글링을 많이해보고 공부한 느낌이 나서 좋은것같습니다

2021-09-26 06:26 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/Storage.cs
> +            this.dataDictionary = new Dictionary<int, T>(datas);
this.dataDictionary = new Dictionary<int, T>(datas); 으로 datas를 가져와서 딥카피를 하고있는데
this.dataDictionary = datas 이렇게 바로 사용하지 않는 이유가 있는건가요?

2021-09-26 06:26 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/Storage.cs
> +            readerType.GetMethod("Read").Invoke(reader, null);
리플렉션 기능으로 GetMethod를 사용해주셨는데,
```c#
var reader = (Reader<T>)Activator.CreateInstance(readerType);
reader.Read();
reader.StoreDatasInStorage();
```
이렇게 사용하는게 더 나을것 같습니다.

GetMethod(string)의 단점
1. 오타로부터 안전하지 않음 즉 컴파일에러가 아닌 런타임에러로 가져갈 수 있기때문
2. 성능면에서 일반 함수실행에 비해 함수를 찾는 비용이 있어서 압도적으로 떨어짐

필수불가결한 상황이라면 사용해야하지만 대체할방법이있다면 지양하는편이 좋습니다

2021-09-26 06:28 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Storage.cs
> +            this.dataDictionary = new Dictionary<int, T>(datas);
c# dictionary 를 키워드로 구글링했을때, copy로 복사 생성자를 사용한다는 내용을 보아서 deep copy를 했습니다.

대입 연산자를 사용해도 깔끔하게 복사가 되는걸까요? (이쪽에 대해 잘 몰라서 질문입니다!)

2021-09-26 06:30 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Storage.cs
> +            readerType.GetMethod("Read").Invoke(reader, null);
오! 제가 원하던 코드입니다. 이런 방식이 가능했군요!!
이렇게 수정하겠습니다. 감사합니다!

2021-09-26 06:31 UTC, JuicyPark commented on Union/Assets/Scripts/Util/Csv/Storage.cs
> +            this.dataDictionary = new Dictionary<int, T>(datas);
대입연산자를 사용하면 얕은복사가 일어나서 레퍼런스 참조가 됩니다.
기존에 datas가 csv로부터 읽어들이는 값이기때문에 변경이 일어나지 않을것같아서, 깊은복사보다는 얕은복사가 더 가벼워서 사용하는게 낫지않을까 생각했습니다.

2021-09-26 06:37 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Storage.cs
> +            this.dataDictionary = new Dictionary<int, T>(datas);
[reader 인스턴스가 사라져도 storage 에서 datas 주소를 참조하고 있기 때문에, gc에서 가져가지 않는다]
그러므로 얕은 복사로 수정합니다! 감사합니다.

2021-09-26 06:48 UTC, JuicyPark approved these changes

2021-09-28 09:40 UTC, Parkhyunseo requested changes

2021-09-28 09:40 UTC, Parkhyunseo commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +            this._csvPath = "Csv/" + typeof(T).Name;
Path Utiliy중 Join 함수 사용하는 게 플랫폼에 맞게 패스를 합칠 수 있을 것 같습니다.
https://docs.microsoft.com/ko-kr/dotnet/api/system.io.path.join?view=net-5.0

2021-09-28 09:40 UTC, Parkhyunseo commented on Union/Assets/Scripts/Util/Csv/Storage.cs
> +        public Dictionary<int, T> datas;
자료구조를 외부로 직접 노출 시키기보다는 함수로 저장, 제거 역할을 주면 좋을 것 같습니다.
그리고 List나 Queue같은 선형적인 타입 말고 Dictionary같은 자료구조를 사용할 때 다들 이름을 어떻게 짓나요?
~s는 뭔가 List같은 모음 같고 ~dict나 ~lib 등 괜찮은 이름이 있을까요

2021-09-28 12:37 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Reader.cs
> +            this._csvPath = "Csv/" + typeof(T).Name;
Path Utility가 있었군요.
Join은 사라졌는지(?), 사용이 안 되서 combine으로 수정했습니다!

2021-09-28 12:39 UTC, GyutaeLee commented on Union/Assets/Scripts/Util/Csv/Storage.cs
> +        public Dictionary<int, T> datas;
실수로 선언이 public으로 되어 있었네요.
기존에도 함수에서만 저장, 제거하고 있었어서 public -> private만 고쳤습니다.

저는 개인 프로젝트 할 때는 List, Queue 선형 타입들은 's', Dictionary 같은 자료구조는 길더라도 dataDictionary 처럼 명확하게 표현해주는 편입니다. (이 프로젝트에서는 s 를 선호하는거 같아서 이렇게 쓰기는 했습니다)

2021-09-29 15:32 UTC, Parkhyunseo commented on Union/Assets/Scripts/Util/Csv/Storage.cs
> +        public Dictionary<int, T> datas;
굳굳 저도 dataDicationary같은 형태로 작성합니다.

2021-09-29 15:33 UTC, Parkhyunseo approved these changes

2021-10-02 06:33 UTC, merged