feat: 캐릭터 컨틀롤러 구현
ECONO-UNION/union-mentoring-1-Unity pull request #6
Opened 2021-08-01 02:27 UTC by Parkhyunseo

* CharacterController사용하지 않고 컨트롤러 구현
* 이동, 달리기, 점프, 앉기 구현

2021-08-01 04:25 UTC, GyutaeLee commented on Union/Assets/Scripts/BaseController.cs
> +                _context.isGrounded = true;
if 문에서 추후에 수정되지 않을 한 줄 코드는 중괄호를 사용하지 않음으로 확고한 "의지"를 담는다.

2021-08-01 04:25 UTC, GyutaeLee approved these changes

2021-08-01 08:11 UTC, JuicyPark requested changes

2021-08-01 08:11 UTC, JuicyPark commented on Union/Assets/Scripts/BaseController.cs
> +        class Context
디폴트 접근제한자는 private을 선언해주세요

2021-08-01 08:11 UTC, JuicyPark commented on Union/Assets/Scripts/BaseController.cs
> +            public abstract void Update(float x, float y);
Non monobehaviour 스크립트에서 Update이름의 함수는 혼동의 여지가 있으니 지양해주세요

2021-08-08 11:54 UTC, JuicyPark approved these changes

2021-08-08 12:06 UTC, merged